##########################################################
##### CURSO Modelado y estimación de ocupación para  #####
#####  poblaciones y comunidades de especies bajo    #####
#####           enfoque Bayesiano.                   #####
#######      CCT Mendoza - ABRIL 2023                #####
##########################################################
##########           Ejemplo GLM/GLMM            #########
##########################################################

rm(list=ls()) #limpio el ambiente de R
library(jagsUI) #paquete JAGS

setwd("") #especifico la ruta de acceso a la ubicacion del archivo

data <- read.csv("ejemplo_AF.csv", header=T)
attach(data)
str(data)


##### GLM - efecto del volumen vegetal - fijo - sin especies ####
win.data <- list(vv = data$vv, centroide = data$centroide, n= nrow(data))

# Modelo
sink("GLM_normal_general.jags")
cat("
model {

  # Priors
  beta0 ~ dnorm(0, 1e-6)
  beta1 ~ dnorm(0, 1e-6)
  sigma ~ dunif(0, 10)
  tau <- 1 / (sigma * sigma)

  # Likelihood
  for (i in 1:n) {
    centroide[i] ~ dnorm(mu[i], tau)
    mu[i] <- beta0 + beta1 * vv[i]

  }
}
",fill = TRUE)
sink()

#valores iniciales
inits <- function() list(beta0 = runif(1, -2, 2), beta1 = runif(1, -3, 3))

# Parametros monitoreados
params <- c("beta0", "beta1")

# MCMC settings
ni <- 10000
nt <- 2
nb <- 1000
nc <- 3

# Call JAGS from R (BRT < 1 min)
out_general <- jags(data = win.data, inits = inits, parameters.to.save = params, 
               model.file = "GLM_normal_general.jags", n.chains = nc, n.thin = nt, 
               n.iter = ni, n.burnin = nb)

save(out_general, file = "out_general") #guardo el out
#load("") # para cargar el out. Especificar la ruta de acceso al archivo 

out_general # Visualización de la salida (out_general)
# JAGS output for model 'GLM_normal_general.jags', generated by jagsUI.
# Estimates based on 3 chains of 10000 iterations,
# adaptation = 100 iterations (sufficient),
# burn-in = 1000 iterations and thin rate = 2,
# yielding 13500 total samples from the joint posterior. 
# MCMC ran for 0.009 minutes at time 2023-03-31 16:00:49.
# 
#             mean    sd    2.5%     50%   97.5% overlap0 f Rhat n.eff
# beta0     28.662 1.552  25.608  28.640  31.708    FALSE 1    1 13500
# beta1     12.822 2.524   7.863  12.828  17.786    FALSE 1    1 13500
# deviance 515.459 2.497 512.612 514.811 521.923    FALSE 1    1 13500
# 
# Successful convergence based on Rhat values (all < 1.1). 
# Rhat is the potential scale reduction factor (at convergence, Rhat=1). 
# For each parameter, n.eff is a crude measure of effective sample size. 
# 
# overlap0 checks if 0 falls in the parameter's 95% credible interval.
# f is the proportion of the posterior with the same sign as the mean;
# i.e., our confidence that the parameter is positive or negative.
# 
# DIC info: (pD = var(deviance)/2) 
# pD = 3.1 and DIC = 518.577 
# DIC is an estimate of expected predictive error (lower is better).

library("denstrip")

#Grafico
plot(out_general$beta0, xlim = c(1,40), ylim =c(0.5,2.5), xlab="", type ="n",
     axes =F, main = "Efecto del vv sin especies")
axis(1)
axis(2, at=1:2, labels = c("beta0", "beta1"), las=1)
for(k in 1:2){
  denstrip(unlist(out_general$sims.list[k]), at = k,
           ticks = out_general$summary[k,c(3,5,7)])
}

out_general
b0 <- out_general$mean$beta0
out_general$sims.listmean$beta0
b1 <- out_general$mean$beta1

tmp <- out_general$sims.list
nsamp <- out_general$mcmc.info$n.samples
vv.pred <- seq(min(data$vv),max(data$vv),length.out = 500) 

pred <- array(NA, dim=c(500,nsamp))
dim(pred)
for(i in 1:nsamp){
  pred[,i]<-plogis(tmp$beta0[i]+tmp$beta1[i]*vv.pred)  #predicci?n para cl
}

pred_general <- array(NA, 500)


for(i in 1:500){
  pred_general[i] <- out_general$mean$beta0 + out_general$mean$beta1*vv.pred[i]
}

plot( data$vv,data$centroide,
     ylab= "Centroide",xlab = "Volumen Vegetal",
     pch=16, bty="l")

lines(vv.pred,pred_general)


##### GLM - ordenada aleatoria por especie ####
win.data <- list(vv = data$vv, centroide = centroide, n = nrow(data),
                 sp = sp_fac)

str(win.data)
# Modelo
sink("GLM_normal_random_ordenada.jags")
cat("
model {

  # Priors
   tau <- pow(sd, -2)
   sd ~ dunif(0,1000)
   beta1 ~ dnorm(0, 1e-6)

  for (k in 1:2) {
    beta0[k]~ dnorm(0, 1e-6)
  }

  # Likelihood
  for (i in 1:n) {
     centroide[i] ~ dnorm(mu[i], tau)
    mu[i] <- beta0[sp[i]] + beta1 * vv[i]
    
    #1 cv
    #2 cm
    }
  }
",fill = TRUE)
sink()


#valores iniciales
inits <- function() list(beta0 = rnorm(2, 3), beta1 = rnorm(1,3))

# Parametros monitoreados
params <- c("beta0", "beta1")

# MCMC settings
ni <- 10000
nt <- 2
nb <- 1000
nc <- 3

# Call JAGS from R (BRT < 1 min)
out_random_ord <- jags(data = win.data, inits = inits, parameters.to.save = params,
                        model.file = "GLM_normal_random_ordenada.jags",
                        n.chains = nc, n.thin = nt,
                        n.iter = ni, n.burnin = nb)

save(out_random_ord, file = "out_random_ordenada")
#load("") 

out_random_ord 

# Grafico
library("denstrip")
plot(out_random_ord$beta0, xlim = c(-20,80), ylim =c(0.5,4.5), xlab="", type ="n",
     axes =F, main = "Ordenada por especie - fijas")
axis(1)
axis(2, at=1:3, labels = c("Cv", "Cm", "Vv"),
     las=1)
abline(v=0)
  denstrip(unlist(out_random_ord$sims.list[[1]][,1]), at =1)
  denstrip(unlist(out_random_ord$sims.list[[1]][,2]), at =2)
  denstrip(unlist(out_random_ord$sims.list[2]), at =3)

#Plot lineas
out_random_ord
vv.pred <- seq(min(data$vv),max(data$vv),length.out = 500) 

ordenada_cv <- array(NA, 500)
  for(i in 1:500){
    ordenada_cv[i] <- out_random_ord$mean$beta0[1] + out_random_ord$mean$beta1*vv.pred[i]
    }
ordenada_cv

ordenada_cm <- array(NA, 500)
for(i in 1:500){
  ordenada_cm[i] <- out_random_ord$mean$beta0[2] + out_random_ord$mean$beta1*vv.pred[i]
}
ordenada_cm

plot(data$vv[data$sp_fac==1],data$centroide[data$sp_fac==1],     #grafico primero solo venustus
        ylab= "Centroide",xlab = "Volumen vegetal",
        pch=16, bty="l", col = "darkred", ylim = c(0,50))
  
points(data$vv[data$sp_fac==2],data$centroide[data$sp_fac==2],     #grafico cm
        pch=16, bty="l", col = "darkorange")

lines(vv.pred,ordenada_cv, col= "darkred")
  
lines(vv.pred,ordenada_cm, col = "darkorange")

  
##### GLM - ordenada y pendiente aleatoria - por especie ####
win.data <- list(vv = data$vv, centroide = centroide, n= nrow(data),
                 sp = sp_fac)

# Modelo
sink("GLM_dos_fijas.jags")
cat("
model {

  # Priors
   tau <- pow(sd, -2)
   sd ~ dunif(0,1000)

  for (k in 1:2) {
    beta0[k]~ dnorm(0, 1e-6)
    beta1[k] ~ dnorm(0, 1e-6)

  }

  # Likelihood
  for (i in 1:n) {
     centroide[i] ~ dnorm(mu[i], tau)
    mu[i] <- beta0[sp[i]] + beta1[sp[i]] * vv[i]
    
    #1 cv
    #2 cm
    }
  }

    ",fill = TRUE)
sink()


#valores iniciales
inits <- function() list(beta0 = rnorm(2, 2), beta1 = rnorm(2,2))

# Parametros monitoreados
params <- c("beta0", "beta1")

# MCMC settings
ni <- 10000
nt <- 2
nb <- 1000
nc <- 3

# Call JAGS from R (BRT < 1 min)
out_dos_fijas <- jags(data = win.data, inits = inits, parameters.to.save = params,
                       model.file = "GLM_dos_fijas.jags", n.chains = nc, n.thin = nt,
                       n.iter = ni, n.burnin = nb)

save(out_dos_fijas, file = "out_dos_fijas")
#load("")

out_dos_fijas 

# Grafico
library("denstrip")
plot(out_dos_fijas$beta0, xlim = c(-20,80), ylim =c(0.5,4.5), xlab="", type ="n",
     axes =F, main = "Especies Fijas ordenada y pendiente")
axis(1)
axis(2, at=1:4, labels = c("B0 Cv", "B0 Cm", "B1 Cv", "B1 Cm"),
     las=1)
abline(v=0)
denstrip(unlist(out_dos_fijas$sims.list[[1]][,1]), at =1)
denstrip(unlist(out_dos_fijas$sims.list[[1]][,2]), at =2)
denstrip(unlist(out_dos_fijas$sims.list[[2]][,1]), at =3)
denstrip(unlist(out_dos_fijas$sims.list[[2]][,2]), at =4)


#Plot lineas
out_dos_fijas
vv.pred <- seq(min(data$vv),max(data$vv),length.out = 500) 

ord_pred_cv <- array(NA, 500)
for(i in 1:500){
  ord_pred_cv[i] <- out_dos_fijas$mean$beta0[1] + out_dos_fijas$mean$beta1[1]*vv.pred[i]
}
ord_pred_cv

ord_pred_cm <- array(NA, 500)
for(i in 1:500){
  ord_pred_cm[i] <- out_dos_fijas$mean$beta0[2] + out_dos_fijas$mean$beta1[2]*vv.pred[i]
}
ord_pred_cm


par(mfrow=c(1,2))

plot(data$vv[data$sp_fac==1],data$centroide[data$sp_fac==1],     #grafico primero solo venustus
     ylab= "Centroide",xlab = "Volumen vegetal",
     pch=16, bty="l", col = "darkred", ylim = c(20,50), main = "GLM ord y pend variable")

points(data$vv[data$sp_fac==2],data$centroide[data$sp_fac==2],     #grafico cm
       pch=16, bty="l", col = "darkorange")

lines(vv.pred,ord_pred_cv, col= "darkred")

lines(vv.pred,ord_pred_cm, col = "darkorange")

##### GLMM - especie aleatoria ####
win.data <- list(vv = data$vv, centroide = centroide, n= nrow(data),
                 sp = sp_fac)

# Modelo
sink("GLMM_random.jags")
cat("
model {

  # Priors
    mu.beta0 ~ dnorm(0, 1e-6)
    tau.beta0 <- pow(sd.beta0, -2)
    sd.beta0 ~ dunif(0, 10)
    mu.beta1 ~ dnorm(0, 1e-6)
    tau.beta1 <- pow(sd.beta1, -2)
    sd.beta1 ~ dunif(0, 10)

   tau <- pow(sd, -2)
   sd ~ dunif(0,1000)

  for (k in 1:2) {
    beta0[k]~ dnorm(mu.beta0, tau.beta0 )
    beta1[k] ~ dnorm(mu.beta1, tau.beta1)
  }

  # Likelihood
  for (i in 1:n) {
     centroide[i] ~ dnorm(mu[i], tau)
    mu[i] <- beta0[sp[i]] + beta1[sp[i]] * vv[i]
    }
  }
",fill = TRUE)
sink()


#valores iniciales
inits <- function() list(beta0 = rnorm(2, 2), beta1 = rnorm(2,2))

# Parametros monitoreados
params <- c("beta0", "beta1", "mu.beta0", "mu.beta1")

# MCMC settings
ni <- 10000
nt <- 2
nb <- 1000
nc <- 3

# Call JAGS from R (BRT < 1 min)
out_random_hiper <- jags(data = win.data, inits = inits, parameters.to.save = params,
                       model.file = "GLMM_random.jags", n.chains = nc, n.thin = nt,
                       n.iter = ni, n.burnin = nb)

save(out_random_hiper, file = "out_random_hiper")
# load("")

out_random_hiper

# Grafico
library("denstrip")
plot(out_random_hiper$beta0, xlim = c(-20,80), ylim =c(0.5,6.5), xlab="", type ="n",
     axes =F, main = "Especies Aleatorias")
axis(1)
axis(2, at=1:6, labels = c("B0 Cv", "B0 Cm", "B1 Cv", "B1 Cm", "Mu B0", "Mu B1"),
     las=1)
abline(v=0)
denstrip(unlist(out_random_hiper$sims.list[[1]][,1]), at =1)
denstrip(unlist(out_random_hiper$sims.list[[1]][,2]), at =2)
denstrip(unlist(out_random_hiper$sims.list[[2]][,1]), at =3)
denstrip(unlist(out_random_hiper$sims.list[[2]][,2]), at =4)
denstrip(unlist(out_random_hiper$sims.list[3]), at =5)
denstrip(unlist(out_random_hiper$sims.list[4]), at =6)

#Plot lineas
vv.pred <- seq(min(data$vv),max(data$vv),length.out = 500) 

pred_cv_ran <- array(NA, 500)
for(i in 1:500){
  pred_cv_ran[i] <- out_random_hiper$mean$beta0[1] + out_random_hiper$mean$beta1[1]*vv.pred[i]
}
pred_cv_ran

ord_cm_ran <- array(NA, 500)
for(i in 1:500){
  ord_cm_ran[i] <- out_random_hiper$mean$beta0[2] + out_random_hiper$mean$beta1[2]*vv.pred[i]
}
ord_cm_ran

#Grafico
plot(data$vv[data$sp_fac==1],data$centroide[data$sp_fac==1],     #grafico primero solo venustus
     ylab= "Centroide",xlab = "Volumen vegetal",
     pch=16, bty="l", col = "darkred", ylim = c(0,50))

points(data$vv[data$sp_fac==2],data$centroide[data$sp_fac==2],     #grafico cm
       pch=16, bty="l", col = "darkorange")

lines(vv.pred,pred_cv_ran, col= "darkred")

lines(vv.pred,ord_cm_ran, col = "darkorange")

##### GLM con interacción - Esoecies fijas ####
win.data <- list(vv = data$vv, centroide = data$centroide, n= nrow(data),
                 sp = sp)

# Modelo
sink("GLM_FIJO.jags")
cat("
model {

  # Priors
  beta0 ~ dnorm(0, 1e-6)
  beta1 ~ dnorm(0, 1e-6)
  beta2 ~ dnorm(0, 1e-6)
  beta3 ~ dnorm(0, 1e-6)
  sigma ~ dunif(0, 10)
  tau <- 1 / (sigma * sigma)

  # Likelihood
  for (i in 1:n) {
    centroide[i] ~ dnorm(mu[i], tau)
    mu[i] <- beta0 + beta1 * vv[i] + beta2 * sp[i] +
             beta3 * sp[i] * vv[i]

  }
}
",fill = TRUE)
sink()



#valores iniciales
inits <- function() list(beta0 = runif(1, -2, 2), beta1 = runif(1, -3, 3),
                         beta2 = runif(1, -3, 3),beta3 = runif(1, -3, 3))

# Parametros monitoreados
params <- c("beta0", "beta1","beta2", "beta3")

# MCMC settings
ni <- 10000
nt <- 2
nb <- 1000
nc <- 3

# Call JAGS from R (BRT < 1 min)
out_FIJOS <- jags(data = win.data, inits = inits, parameters.to.save = params,
                  model.file = "GLM_FIJO.jags", n.chains = nc, n.thin = nt,
                  n.iter = ni, n.burnin = nb)

save(out_FIJOS, file = "out_FIJOS")
load("~/Documentos/TRABAJO/Curso Ocupacion Mendoza/out_FIJOS")

out_random_hiper

#Grafico
library("denstrip")
plot(out_FIJOS$beta0, xlim = c(-20,80), ylim =c(0.5,4.5), xlab="", type ="n",
     axes =F, main = " Fijos Especies")
axis(1)
axis(2, at=1:4, labels = c("beta0 cv", "beta1 vv", "beta2 cm", "beta 3 int"),
     las=1)
abline(v=0)
for(k in 1:5){
  denstrip(unlist(out_FIJOS$sims.list[k]), at = k)
}


#Plot lineas
vv.pred <- seq(min(data$vv),max(data$vv),length.out = 500) 

cv_FIJO <- array(NA, 500)
for(i in 1:500){
  cv_FIJO[i] <- out_FIJOS$mean$beta0 + out_FIJOS$mean$beta1 * vv.pred[i] + 
                out_FIJOS$mean$beta2 * 0 + out_FIJOS$mean$beta3 * vv.pred[i] * 0 
}
cv_FIJO

cm_FIJO <- array(NA, 500)
for(i in 1:500){
  cm_FIJO[i] <- out_FIJOS$mean$beta0 + out_FIJOS$mean$beta1 * vv.pred[i] + 
    out_FIJOS$mean$beta2 * 1 + out_FIJOS$mean$beta3 * vv.pred[i] * 1 
}
cm_FIJO


#Grafico
plot(data$vv[data$sp_fac==1],data$centroide[data$sp_fac==1],     #grafico primero solo venustus
     ylab= "Centroide",xlab = "Volumen vegetal",
     pch=16, bty="l", col = "darkred", ylim = c(20,50), main = "GLM interaccion")

points(data$vv[data$sp_fac==2],data$centroide[data$sp_fac==2],     #grafico cm
       pch=16, bty="l", col = "darkorange")

lines(vv.pred,cv_FIJO, col= "darkred")

lines(vv.pred,cm_FIJO, col = "darkorange")

