##~~~~~Determining the presence of a species~~~~~~~~~~####
## Macarthy 
# Bayesian Methos for ecology

library(jagsUI)    #paquete JAGS

sink("modelo1.jags")  
cat("
model
{
  prior <- 0.5                  # the prior probability 
                                # of presence
  present ~ dbern(prior)        # actual presence drawn 
                                # from a Bernoulli dist’n
  prob_detect <- 0.8 * present  # prob of detection depends 
                                # on presence/absence
  detected ~ dbern(prob_detect) # actual detection occurs 
                                #  with random variation
}

    ", fill=TRUE)
sink()

data <- list(detected = 0)              # the data - the frog was not detected

# ajustes de MCMC
ni <- 100000
nt <- 10
nb <- 10000
nc <- 3

# Parametros
params1 <- c("present", "detected")

inits <- function (){
  list (present = runif(1) )
}

out <- jags(data,inits, params1,"modelo1.jags", n.chains=nc, 
              n.iter=ni, n.burnin=nb, n.thin=nt)


# JAGS output for model 'modelo1.jags', generated by jagsUI.
# Estimates based on 3 chains of 1e+05 iterations,
# adaptation = 100 iterations (sufficient),
# burn-in = 10000 iterations and thin rate = 10,
# yielding 27000 total samples from the joint posterior. 
# MCMC ran for 0.001 minutes at time 2023-03-11 10:47:55.
# 
#           mean    sd 2.5% 50% 97.5% overlap0 f Rhat n.eff
# present  0.167 0.373    0   0 1.000     TRUE 1    1 27000
# deviance 0.539 1.201    0   0 3.219     TRUE 1    1 27000



# present: 0.17
# Estimador de la probabilidad posterior de que el sitio está ocupada
#dada la probabilidad previa y  los datos. 
#si se cambia la previa a 0.75, la probabilidad es de 0.38.



## ~~~~~~~~Estimación de media~~~~~~~~~~~~~~####

### NO ANDA POR ALGO ###

# Diametro promedio de árboles en un parque de bosque de eucalipto

# Un investigador ha medido aleatoriamente el diámetro de arboles
# Anteriormente ya habia medido mas de 2500 árboles en otros 43 sitios
# Esto le permite tener una idea de los diámteros de de los arboles-

# El diametro previo es 53 cm y el desvío es de 5cm.
# Assuming the mean diameter of trees follows a normal distribution,
# we would expect approximately 95% of remnants to have a mean tree 
# diameter that is within 1.96 standard deviations of the overall average.

# La presición que es la que se usa, es de 0.04 (1/varianza)
library(jagsUI)    #paquete JAGS

# Agrupar los datos en una lista para que pueda ser leida por JAGS
data <- list(Y = c(42, 43, 58, 70, 47, 51, 85, 63, 58, 46))

# Modelo
sink("media.jags")
cat("
model
{
  m~dnorm(53, 0.04)
  stdev <- sd(Y[])
  
prec <- 1/(stdev*stdev)  
  for (i in 1:10)
  {
    Y[i] ~ dnorm(m, prec)
    }
  
}

",fill = TRUE)
sink()

#MCMC settings
ni <- 100000
nt <- 2
nb <- 1000
nc <- 3

#Parametros
parameters <- c("m","prec")

#Run JAGS model
out <- jags(data, 
            inits=NULL, 
            parameters, 
            "media.jags", 
            n.chains = nc, 
            n.thin = nt, 
            n.iter = ni,
            n.burnin = nb)





## ~~~~~~~~Estimación de media~~~~~~~~~~~~~~####

# Diametro promedio de árboles en un parque de bosque de eucalipto

# Incluye previas no informativas, con incertidumbre en la varianza,
# a diferencia del ejemplo anterior donde se asume que es un valor conocido

# La presición que es la que se usa, es de 0.04 (1/varianza)
library(jagsUI)    #paquete JAGS

# Agrupar los datos en una lista para que pueda ser leida por JAGS
data <- list(Y = c(42, 43, 58, 70, 47, 51, 85, 63, 58, 46))

# Modelo
sink("media-1.jags")
cat("
model
    {
        mean ~ dnorm(0, 1.0E-6)
        var ~ dlnorm(0.0, 1.0E-6)
        prec <- 1/var
    
    for(1 in 1:10)
    {
    Y[i] ~ dnorm(mean, prec)     # tree diameter drawn from normal distribution
    }
    
}

",fill = TRUE)
sink()

#MCMC settings
ni <- 100000
nt <- 2
nb <- 1000
nc <- 3

#Parametros
parameters <- c("m","prec")

# Initial values
inits <- function() list(var = 100, mean = 100)

#Run JAGS model
out <- jags(data, 
            inits, 
            parameters, 
            "media-1.jags", 
            n.chains = nc, 
            n.thin = nt, 
            n.iter = ni,
            n.burnin = nb)




## ~~~~~~~~Estimación de media con Poisson~~~~~~~~~~~~~~####

# Investigadores en NY midieron la densidad de arboles en 10 cuadrantes (400m2 c/U)
# en Van Cortlandt Park

# Una distribución previa no informativa para la densidad media del red oak en cda cuadrante
# debe tomar valores positivos y tener una amplia distribucion.

#Una distribución lonormal que tenga media 0 y desvio standar 1000 para valores 
# log-transform puede funcionar.


# La presición que es la que se usa, es de 0.04 (1/varianza)
library(jagsUI)    #paquete JAGS

# Agrupar los datos en una lista para que pueda ser leida por JAGS
data <- list(y = c(6,0,1,2,1,7,1,5,2,0))

# Modelo
sink("media-poisson.jags")
cat("
model
{
  for (i in 1:10)
  {
    y[i] ~ dpois (m)
    }
  
  m ~ dlnorm(0.0, 1.0E-6)
}

",fill = TRUE)
sink()

#MCMC settings
ni <- 100000
nt <- 2
nb <- 10000
nc <- 3

#Parametros
parameters <- c("m")

inits <- function() list(m = 5)

#Run JAGS model
out <- jags(data, 
            inits=inits, 
            parameters, 
            "media-poisson.jags", 
            n.chains = nc, 
            n.thin = nt, 
            n.iter = ni,
            n.burnin = nb)




## ~~~~~~~~Estimación de media con Poisson~~~~~~~~~~~~~~####
### Con variacion entre la densidad promedio de los caudarte###


# Investigadores en NY midieron la densidad de arboles en 10 cuadrantes (400m2 c/U)
# en Van Cortlandt Park

# Una distribución previa no informativa para la densidad media del red oak en cda cuadrante
# debe tomar valores positivos y tener una amplia distribucion.

#Una distribución lonormal que tenga media 0 y desvio standar 1000 para valores 
# log-transform puede funcionar.


# La presición que es la que se usa, es de 0.04 (1/varianza)
library(jagsUI)    #paquete JAGS

# Agrupar los datos en una lista para que pueda ser leida por JAGS
data <- list(y = c(6,0,1,2,1,7,1,5,2,0))

# Modelo
sink("media-poisson-variacion.jags")
cat("
model
{
  for (i in 1:10)        # for each of the 10 quadrants
  {
    mean[i] ~ dlnorm(m, tau)   # mean density drawn from lognormal
    y[i] ~ dpois (mean[i])     # no. of plants drawn from Poisson
    }
  
  m ~ dlnorm(0, 1.0E-6)       # mean of the log density of plants
  sd ~ dunif(0,10)            # sd of the log density of plants
  
  tau <- 1/(sd*sd)
}

",fill = TRUE)
sink()

#MCMC settings
ni <- 100000
nt <- 2
nb <- 10000
nc <- 3

#Parametros
parameters <- c("mean")

inits <- function() list(m = 5)

#Run JAGS model
out <- jags(data, 
            inits=inits, 
            parameters, 
            "media-poisson-variacion.jags", 
            n.chains = nc, 
            n.thin = nt, 
            n.iter = ni,
            n.burnin = nb)
out




